require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Metrics/ClassLength:
  Max: 120
